packages/core/src/index.ts
packages/core/src/types/list.types.ts
packages/core/src/utils/list.utils.ts

Related to https://github.com/buildwithjuno/juno/issues/47

feat: order with timestamps updated_at and created_at

---

packages/core/src/constants/auth.constants.ts
packages/core/src/index.ts
packages/core/src/providers/auth.providers.ts
packages/core/src/services/auth.services.ts
packages/core/src/services/user.services.ts
packages/core/src/stores/auth.store.ts
packages/core/src/types/auth.types.ts
packages/core/src/utils/auth.utils.ts

Additional authentication provider: [NFID](https://nfid.one/)

feat: NFID

---

.github/workflows/publish.yml
package-lock.json
package.json
packages/ledger/package.json
packages/utils/LICENSE
packages/utils/README.md
packages/utils/esbuild.mjs
packages/utils/package.json
packages/utils/src/index.ts
packages/utils/src/utils/did.utils.ts
packages/utils/src/utils/null.utils.ts
packages/utils/tsconfig.json

feat: utils

---

packages/core/src/api/doc.api.ts
packages/core/src/services/doc.services.ts

https://twitter.com/daviddalbusco/status/1677309300971061256

feat: rename delDoc to deleteDoc

---

packages/admin/declarations/satellite/satellite.did.d.ts
packages/admin/declarations/satellite/satellite.factory.did.js
packages/admin/declarations/satellite/satellite.factory.did.mjs
packages/admin/src/constants/config.constants.ts
packages/admin/src/services/satellite.services.ts
packages/admin/src/types/config.types.ts
packages/core/declarations/satellite/satellite.did.d.ts
packages/core/declarations/satellite/satellite.factory.did.js
packages/core/declarations/satellite/satellite.factory.did.mjs

Relates to https://github.com/buildwithjuno/juno/issues/167

feat: support for storage rewrites url

---

packages/admin/src/utils/actor.utils.ts
packages/analytics/src/utils/actor.utils.ts
packages/core/src/utils/actor.utils.ts

feat: https://icp-api.io instead of icp.io of actors

---

packages/admin/declarations/orbiter/orbiter.did.d.ts
packages/admin/declarations/orbiter/orbiter.factory.did.js
packages/analytics/declarations/orbiter/orbiter.did.d.ts
packages/analytics/declarations/orbiter/orbiter.factory.did.js
packages/analytics/src/services/analytics.services.ts
packages/analytics/src/services/idb.services.ts
packages/analytics/src/types/idb.ts
packages/analytics/src/workers/analytics.worker.ts
packages/core/declarations/orbiter/orbiter.did.d.ts
packages/core/declarations/orbiter/orbiter.factory.did.js

Relates to https://github.com/buildwithjuno/juno/pull/221

feat: orbiter collected at as key

---

package-lock.json
packages/core/package.json
scripts/update-agent

Because of TypeScript it's actually useful to have dependencies

build: revert dev dependencies

---

packages/core/src/workers/auth.worker.ts

feat: provide the delegation expiration time

---

packages/admin/src/api/satellite.api.ts
packages/admin/src/services/satellite.services.ts
packages/core/src/api/doc.api.ts
packages/core/src/api/storage.api.ts
packages/core/src/services/doc.services.ts
packages/core/src/services/storage.services.ts

feat: move countDocs|Assets and listDocs|Assets to admin

---

packages/core/src/api/actor.api.ts
packages/core/src/services/storage.services.ts
packages/core/src/utils/env.utils.ts

fix: "satelliteUrl" in NodeJS context

---

packages/admin/src/api/ic.api.ts
packages/admin/src/services/mission-control.services.ts
packages/admin/src/services/orbiter.services.ts
packages/admin/src/services/satellite.services.ts
packages/admin/src/types/ic.types.ts

The install_code mode params have been updated on the IC through Candid in a breaking change way...
https://internetcomputer.org/docs/current/references/ic-interface-spec/#ic-install_code

feat: IC candid breaking changes

---

packages/admin/declarations/satellite/satellite.did.d.ts
packages/admin/declarations/satellite/satellite.factory.did.js
packages/admin/declarations/satellite/satellite.factory.did.mjs
packages/admin/src/api/satellite.api.ts
packages/admin/src/services/satellite.services.ts
packages/config/src/index.ts
packages/config/src/mainnet/authentication.config.ts
packages/config/src/mainnet/satellite.config.ts
packages/core/declarations/satellite/satellite.did.d.ts
packages/core/declarations/satellite/satellite.factory.did.js
packages/core/declarations/satellite/satellite.factory.did.mjs

Relates to https://github.com/junobuild/juno/issues/156

feat: derivation and auth config

---

packages/config/README.md
packages/config/src/satellite/dev/juno.dev.config.ts

feat: datastore instead of db for dev config

---

packages/config-loader/src/configs/juno.config.ts

Related to https://github.com/junobuild/cli/issues/120

feat: detect juno config type

---

packages/admin/declarations/satellite/satellite.did.d.ts
packages/admin/declarations/satellite/satellite.factory.did.js
packages/admin/declarations/satellite/satellite.factory.did.mjs
packages/console/declarations/console/console.did.d.ts
packages/console/declarations/console/console.factory.did.js
packages/console/declarations/console/console.factory.did.mjs
packages/console/src/api/proposal.api.ts
packages/core/declarations/satellite/satellite.did.d.ts
packages/core/declarations/satellite/satellite.factory.did.js
packages/core/declarations/satellite/satellite.factory.did.mjs
packages/core/src/types/list.types.ts
packages/core/src/utils/list.utils.ts
packages/storage/declarations/console/console.did.d.ts
packages/storage/declarations/console/console.factory.did.js
packages/storage/declarations/console/console.factory.did.mjs
packages/storage/declarations/satellite/satellite.did.d.ts
packages/storage/declarations/satellite/satellite.factory.did.js
packages/storage/declarations/satellite/satellite.factory.did.mjs

Relates to https://github.com/junobuild/juno/issues/651

feat: updated_at and created_at filters

---

packages/admin/declarations/satellite/satellite.did.d.ts
packages/admin/declarations/satellite/satellite.factory.did.js
packages/admin/declarations/satellite/satellite.factory.did.mjs
packages/core/declarations/satellite/satellite.did.d.ts
packages/core/declarations/satellite/satellite.factory.did.js
packages/core/declarations/satellite/satellite.factory.did.mjs
packages/core/src/api/doc.api.ts
packages/core/src/api/storage.api.ts
packages/core/src/services/doc.services.ts
packages/core/src/services/storage.services.ts
packages/storage/declarations/satellite/satellite.did.d.ts
packages/storage/declarations/satellite/satellite.factory.did.js
packages/storage/declarations/satellite/satellite.factory.did.mjs

Relates to https://github.com/junobuild/juno/pull/702

feat: countDocs and countAssets

---

package-lock.json
packages/admin/package.json
packages/console/package.json
packages/core-peer/package.json
packages/core/package.json
packages/storage/package.json
packages/utils/package.json

Agent-js > 2.0.0 to <= 2.1.2 was incompatible with IC mgmt calls.

build: agent-js v2.1.3

---

packages/config/README.md
packages/config/src/satellite/mainnet/configs/satellite.config.ts

A type mostly use to generate nice readme

feat: satellite config options type

---

packages/admin/src/handlers/upgrade.handlers.ts
packages/admin/src/types/upgrade.types.ts

Not really beautiful but, I cannot come up with another pattern as we need to display the status of each step in the UI. e.g. Because of the stepper we might want to display that the upgrade failed and that we are restarting the module.

feat: upgrade progress status

---

package-lock.json
packages/admin/package.json
packages/admin/src/handlers/upgrade.handlers.ts

Enable the support for upgrading WASM > 2MB

feat: enable chunked wasm upgrade

---

package-lock.json
packages/admin/package.json
packages/console/package.json
packages/core-peer/package.json
packages/core/package.json
packages/storage/package.json
scripts/update-agent

If we want to be precise in the list of peer dependencies, candid is also one.

build: candid peer dependencies

---

packages/admin/declarations/mission_control/mission_control.did.d.ts
packages/admin/declarations/mission_control/mission_control.factory.did.js
packages/console/declarations/console/console.did.d.ts
packages/console/declarations/console/console.factory.did.js
packages/console/declarations/console/console.factory.did.mjs
packages/storage/declarations/console/console.did.d.ts
packages/storage/declarations/console/console.factory.did.js
packages/storage/declarations/console/console.factory.did.mjs

Update the did files with all the changes that happened when the new monitoring feature was developed.
No impact on the JS libs.

feat: update did for monitoring feature

---

package-lock.json
package.json
packages/analytics/package.json
scripts/update-agent

fix: analytics require DFINITY agent as peer too

---

packages/core/src/services/auth.services.ts

fix: re-create immediately agent after sign-out

---

packages/core/src/index.ts
packages/core/src/services/auth.services.ts
packages/core/src/types/errors.types.ts

feat: throw error if client not initialized on signIn

---

packages/core/src/services/auth.services.ts

PR #240 has ovewritten #239 which was necessary. I f*cked up something in Webstorm while switching branch...

fix: redo re-create immediately agent after sign-out

---

packages/admin/src/api/satellite.api.ts
packages/admin/src/constants/rules.constants.ts
packages/admin/src/services/satellite.config.services.ts
packages/admin/src/utils/rule.utils.ts
packages/config/README.md
packages/config/src/satellite/mainnet/configs/authentication.config.ts
packages/config/src/satellite/types/rules.ts

Satellite v0.0.22 offers various new optional configuration options.
https://github.com/junobuild/juno/releases/tag/v0.0.44

feat: admin support for max_changes_per_user and external_alternative_origins

---

packages/functions/README.md
packages/functions/src/schemas/candid.ts
packages/functions/src/schemas/core.ts
packages/functions/src/sdk/db.sdk.ts
packages/functions/src/sdk/schemas/db.ts
packages/functions/src/tests/schemas/candid.spec.ts
packages/functions/src/tests/schemas/core.spec.ts
packages/functions/src/tests/sdk/db.sdk.spec.ts
packages/functions/src/tests/sdk/schemas/db.spec.ts

It will be convenient to accept both principal and rawprincipal in the sdk.

feat: accept principal as well in setDocStore

---

packages/functions/README.md
packages/functions/src/ic-cdk/call.ic-cdk.ts
packages/functions/src/ic-cdk/schemas/call.ts
packages/functions/src/tests/ic-cdk/call.ic-cdk.spec.ts
packages/functions/src/tests/ic-cdk/schemas/call.spec.ts

A function might require no argument

feat: args optional

---

packages/functions/src/hooks/db/assertions.ts

Better readability if we add more assertions.

refactor: use union instead of or

---

packages/functions/README.md
packages/functions/src/hooks/schemas/context.ts
packages/functions/src/hooks/schemas/db/context.ts

Fix
```
doc: DocContext<DocUpsert>}
does not satisfy the constraint ZodTypeAny
```

fix: typescript and zod type infer

---

packages/functions/README.md
packages/functions/src/hooks/schemas/db/payload.ts

fix: incorrect DelDoc infer type

---

packages/functions/README.md
packages/functions/src/sdk/db.sdk.ts
packages/functions/src/sdk/schemas/db.ts
packages/functions/src/tests/sdk/db.sdk.spec.ts
packages/functions/src/tests/sdk/schemas/db.spec.ts

Have the key outside of the doc is more consistent.

feat: cleaner setDocStore interface

---

packages/functions/README.md
packages/functions/src/global.d.ts
packages/functions/src/sdk/db.sdk.ts
packages/functions/src/sdk/schemas/db.ts
packages/functions/src/tests/sdk/db.sdk.spec.ts
packages/functions/src/tests/sdk/schemas/db.spec.ts

JS bindings for https://github.com/junobuild/juno/pull/1444

feat: getDocStore

---

package-lock.json

Resolves https://github.com/junobuild/juno-js/security/dependabot/28

build: patch vite security issue

---

packages/functions/README.md
packages/functions/src/global.d.ts
packages/functions/src/sdk/db.sdk.ts
packages/functions/src/tests/sdk/db.sdk.spec.ts

Relates to https://github.com/junobuild/juno/pull/1446

feat: return values for setDocStore and deleteDocStore

---

packages/functions/README.md
packages/functions/src/global.d.ts
packages/functions/src/schemas/list.ts
packages/functions/src/sdk/db.sdk.ts
packages/functions/src/sdk/schemas/db.ts
packages/functions/src/tests/schemas/list.spec.ts
packages/functions/src/tests/sdk/db.sdk.spec.ts
packages/functions/src/tests/sdk/schemas/db.spec.ts

Relates to https://github.com/junobuild/juno/pull/1447

feat: SDK listDocsStore

---

packages/functions/README.md
packages/functions/src/global.d.ts
packages/functions/src/sdk/db.sdk.ts
packages/functions/src/sdk/schemas/db.ts
packages/functions/src/tests/sdk/db.sdk.spec.ts
packages/functions/src/tests/sdk/schemas/db.spec.ts

Relates to https://github.com/junobuild/juno/pull/1449

feat: SDK count docs store

---

packages/functions/README.md
packages/functions/src/global.d.ts
packages/functions/src/sdk/db.sdk.ts
packages/functions/src/sdk/schemas/db.ts
packages/functions/src/tests/sdk/db.sdk.spec.ts

Relates to https://github.com/junobuild/juno/pull/1450

feat: SDK deleteDocsStore and deleteFilteredDocsStore

---

packages/functions/README.md
packages/functions/src/sdk.ts
packages/functions/src/sdk/db.sdk.ts
packages/functions/src/sdk/schemas/db.ts
packages/functions/src/sdk/schemas/params.ts
packages/functions/src/tests/sdk/db.sdk.spec.ts
packages/functions/src/tests/sdk/schemas/db.spec.ts
packages/functions/src/tests/sdk/schemas/params.spec.ts

We will reuse those for the SDK storage.

refactor: extract params

---

packages/functions/README.md
packages/functions/src/global.d.ts
packages/functions/src/schemas/storage.ts
packages/functions/src/sdk/schemas/storage.ts
packages/functions/src/sdk/storage.sdk.ts
packages/functions/src/tests/schemas/storage.spec.ts
packages/functions/src/tests/sdk/schemas/storage.spec.ts
packages/functions/src/tests/sdk/storage.sdk.spec.ts

Relates to https://github.com/junobuild/juno/pull/1454

feat: SDK setAssetHandler

---

packages/functions/README.md
packages/functions/src/global.d.ts
packages/functions/src/schemas/storage.ts
packages/functions/src/sdk/schemas/storage.ts
packages/functions/src/sdk/storage.sdk.ts
packages/functions/src/tests/schemas/storage.spec.ts
packages/functions/src/tests/sdk/schemas/storage.spec.ts
packages/functions/src/tests/sdk/storage.sdk.spec.ts

Relatest to https://github.com/junobuild/juno/pull/1459

feat: SDK delete assets

---

packages/config/README.md
packages/config/src/satellite/mainnet/configs/orbiter.config.ts
packages/config/src/satellite/mainnet/juno.config.ts

feat: ids for orbiter config

---

package-lock.json
package.json

We bump `@dfinity/eslint-config-oisy-wallet` to the latest version.

build: bump eslint library

---

packages/errors/src/constants.ts

We also want to provide constants for the errors in the collections.

feat: collections errors

---

packages/admin/src/types/actor.types.ts
packages/admin/src/utils/actor.utils.ts
packages/cdn/src/types/actor.types.ts
packages/cdn/src/types/console.types.ts
packages/cdn/src/utils/actor.utils.ts
packages/core/src/stores/actor.store.ts
packages/core/src/stores/agent.store.ts
packages/core/src/types/satellite.types.ts

NodeJS supports natively fetch for a long time now.

feat: deprecate fetch options

---

packages/cli-tools/src/commands/publish.ts
packages/cli-tools/src/constants/deploy.constants.ts
packages/cli-tools/src/services/deploy.proposal.services.ts
packages/cli-tools/src/services/upload.services.ts

Relates to https://github.com/junobuild/juno/pull/1660

feat: narrow collection #_juno/releases

---

packages/config/README.md
packages/config/src/console/console.config.ts
packages/config/src/satellite/mainnet/configs/orbiter.config.ts
packages/config/src/satellite/mainnet/configs/satellite.config.ts
packages/config/src/tests/satellite/mainnet/configs/authentication.config.spec.ts
packages/config/src/tests/satellite/mainnet/configs/orbiter.config.spec.ts
packages/config/src/tests/satellite/mainnet/configs/satellite.config.spec.ts
packages/config/src/tests/satellite/mainnet/juno.config.spec.ts
packages/config/src/tests/utils/principal.utils.spec.ts
packages/config/src/utils/principal.utils.ts

I reverted to Zod v3 but, using the latest version of the Zod library which seems to contains breaking changes for v3 as well.

feat(config): fix zod validation

---

packages/core/src/index.ts
packages/core/src/services/auth.services.ts

feat(core): getIdentityOnce

---

packages/core/src/api/_actor.factory.ts
packages/core/src/api/actor.api.ts
packages/core/src/api/storage.api.ts
packages/core/src/tests/api/actor.api.spec.ts
packages/core/src/tests/stores/actor.store.spec.ts

I felt like its cleaner to have one module only with those weird imports.

refactor(core): actor factory

---

packages/config/README.md
packages/config/src/index.ts
packages/config/src/satellite/configs/collections.ts
packages/config/src/satellite/dev/juno.dev.config.ts
packages/config/src/tests/satellite/configs/collections.spec.ts
packages/config/src/tests/satellite/dev/juno.dev.config.spec.ts

Relates to https://github.com/junobuild/cli/issues/302

feat: extract collections config

---

packages/config/README.md
packages/config/src/index.ts
packages/config/src/satellite/configs/collections.ts
packages/config/src/satellite/dev/juno.dev.config.ts
packages/config/src/satellite/mainnet/configs/datastore.config.ts
packages/config/src/tests/satellite/configs/collections.spec.ts
packages/config/src/tests/satellite/dev/juno.dev.config.spec.ts

https://github.com/junobuild/cli/issues/302

feat(config): Datastore instead of DataStore for consistency

---

packages/config/README.md
packages/config/src/satellite/mainnet/configs/satellite.config.ts
packages/config/src/tests/satellite/mainnet/configs/satellite.config.spec.ts

After thinking at it, maybe cleaner to have the collections separate and not nested with the rest of the config.
And I want to avoid breakign changes too.
Relates to https://github.com/junobuild/cli/issues/302

feat: collections as a separate config

---

packages/config/README.md
packages/config/src/satellite/mainnet/configs/datastore.config.ts
packages/config/src/shared/storage.config.ts
packages/config/src/tests/satellite/mainnet/configs/datastore.config.spec.ts
packages/config/src/tests/shared/storage.config.spec.ts

After thinking at it, better to have the collections separate.
Follow-up of #470
Relates to https://github.com/junobuild/cli/issues/302

feat(config): remove nested collections

---

packages/cli-tools/src/services/deploy.prepare.services.ts
packages/cli-tools/src/utils/compress.utils.ts
packages/config/README.md
packages/config/src/tests/types/cli.config.spec.ts
packages/config/src/types/cli.config.ts

Resolves https://github.com/junobuild/cli/issues/108

feat(cli-tools): brotli compression

---

packages/errors/src/constants/satellite.constants.ts

feat(errors): user webauthn error keys

---

.prettierignore
eslint.config.ts
package.json

chore(rules): setup prettier with exclude instead of pre-cleaning

---

packages/core/src/auth/services/auth.services.ts
packages/core/src/auth/types/auth.ts
packages/core/src/tests/auth/services/auth.services.spec.ts

feat(core): window.location.reload on signOut

---

package-lock.json
packages/core-peer/package.json
packages/core/package.json
packages/did-tools/package.json
packages/ic-client/package.json
packages/utils/package.json

Follow-up and leftovers of #577

feat(repo): use dfinity utils with Principal.isPrincipal for jsonReplacer (part 2)

---

packages/config/README.md
packages/config/src/satellite/configs/emulator.config.ts
packages/config/src/satellite/validators/emulator.validators.ts
packages/config/src/tests/satellite/configs/emulator.config.spec.ts
packages/config/src/tests/satellite/validators/emulator.validators.spec.ts

This service or that service needs this service or that service. Let's just validate that early for a better DX.

feat(config): emulator validators

---

packages/config/README.md
packages/config/src/satellite/configs/emulator.config.ts
packages/config/src/tests/satellite/configs/emulator.config.spec.ts

Relates to https://github.com/junobuild/juno-docker/pull/199

feat(config): timeout for emulator ports
