- packages/core/src/api/storage.api.ts
- packages/core/src/services/storage.services.ts
For consistency reason and because the storage does not check for timestamp when writing and deleting.
Last operation wins unlike in the Datastore.
> feat: replace parameter storageFile with fullPath (only) in deleteAsset

- package-lock.json
- packages/admin/package.json
- packages/core/esbuild.mjs
- packages/core/package.json
- packages/ledger/package.json
- scripts/update-agent
No other way, it's just impossible to ship a library that contains agent-js to next.js - i.e. agent-js has to be installed by next to be bundled with webpack otherwise the library and app fails in production at runtime.
Fortunately, `npm i` does automatically install peer dependencies. Yarn doesn't though.
Bump agent-js at the same time.
> build: agent-js as peer dependency of core

- packages/admin/src/utils/rule.utils.ts
- packages/config/README.md
- packages/config/src/dev/juno.dev.config.ts
- packages/config/src/types/rules.ts
One type has underscore, the other not, one has a capital letter, the other not etc.
Let's be consistent even if it means rolling out a breaking changes (in the lib) once.
> feat: cleanup JavaScript Rule type (breaking change)

- packages/analytics/src/services/analytics.services.ts
- packages/analytics/src/utils/log.utils.ts
Resolves #142
To some extension, if there is an error at runtime, not initializing the analytics worker should not block the user. Missing some analytics is less important that breaking user experience.
> feat: warning instead of error if analytics worker not initialized

- packages/core/src/services/storage.services.ts
- packages/core/src/types/storage.types.ts
`listDocs` returns `items` and the website also document `items` for both `listAssets` and `listDocs`, so, let's use `items` for `listAssets` as well.
Backwards compatible.
> feat: returns also items for listAssets

- packages/admin/src/index.ts
- packages/admin/src/services/module.upgrade.services.ts
Needed for Juno Docker to support WASM > 2MB without reinventing the wheel
> feat: expose upgrade module

- packages/admin/src/api/ic.api.ts
- packages/admin/src/handlers/upgrade.handlers.ts
- packages/admin/src/services/mission-control.upgrade.services.ts
- packages/admin/src/services/orbiter.upgrade.services.ts
- packages/admin/src/services/satellite.upgrade.services.ts
- packages/admin/src/types/upgrade.types.ts
YASSSSS! I had waited for snapshots in the upgrade process for years, the wait is over.
> feat: take snapshot on upgrade

- .gitignore
- README.md
- package-lock.json
- package.json
- packages/core-standalone/README.md
- packages/core-standalone/esbuild.mjs
- packages/core-standalone/package.json
- packages/core-standalone/tsconfig.json
- scripts/build-next
- scripts/license.sh
- scripts/publish-npm-next.sh
- scripts/publish-npm.sh
- scripts/update-agent
We gonna shift the approach by making `@junobuild/core` using agent-js with peer dependencies, deprecate `@junobuild/core-peer` and introduce `@junobuild/core-standalone` with everything included.
> feat: init standalone library

- package-lock.json
- package.json
- packages/core/package.json
- scripts/update-agent
We want to ease the onboarding and also resolve the confusion about when peer and when not peer. So we are going to use peer dependencies per default, handle this in the doc and provide a standalone package.
> feat: core use agent-js as peer dependencies

- package-lock.json
- package.json
- packages/core-peer/package.json
- packages/core-standalone/package.json
- packages/core/package.json
We want to improve a bit semver by starting using v0.x.y.
x for breaking changes.
> chore: version v0.1.0 for core

- packages/core/src/services/auth.services.ts
- packages/core/src/types/errors.types.ts
It's a bit cleaner to have a specific error type for this edge case
> feat: SignInInitError when authclient not initialized

- package-lock.json
- packages/core/package.json
- packages/core/src/services/user.services.ts
- packages/errors/src/index.ts
- packages/errors/src/utils.ts
See comment in code. This is meant to prevent an edge case given that has of next version of the Satellite, users cannot update their entity anymore.
> feat: retry get user on sign-in

- packages/errors/package.json
As discovered in https://github.com/junobuild/juno/pull/1264 the types are missing in the new library
> fix: missing types for junobuild/errors

- packages/cli-tools/src/utils/cmd.utils.ts
We need to extend `juno dev build` to pass `RUSTFLAGS='--cfg getrandom_backend="custom"'` for getrandom 0.3.0
> feat: extend execute and spawn commands with env

- packages/functions/README.md
- packages/functions/src/configs/assert.config.ts
- packages/functions/src/configs/hook.config.ts
- packages/functions/src/tests/configs/assert.config.spec.ts
- packages/functions/src/tests/configs/hook.config.spec.ts
This way we avoid duplication on usage.
Instead of:
```
export const onSetDoc = defineHook({
collections: ['demo', 'console'],
onSetDoc: async (context: OnSetDocContext) => {
console.log('onSetDoc');
}
});
```
we can have
```
export const onSetDoc = defineHook<OnSetDocConfig>({
collections: ['demo', 'console'],
run: async (context) => {
console.log('onSetDoc');
}
});
```
> feat: review functions api to avoid duplication

- package.json
- packages/functions/.gitignore
- packages/functions/package.json
- scripts/esbuild-functions.mjs
- scripts/esbuild-pkg.mjs
- scripts/esbuild-utils.mjs
- scripts/esbuild.mjs
I want to ship the functions library as a multi-entry library (B.), kind of feel like it's cooler and more modern.
```
// A.
import { icCdkId, setDocStore } from '@junobuild/functions';
console.log(icCdkId());
// B.
import { setDocStore } from '@junobuild/functions/sdk';
import { id } from '@junobuild/functions/ic-cdk';
console.log(id());
```
> build: functions as multi-entry library

- packages/functions/README.md
- packages/functions/src/hooks/schemas/collections.ts
We want to accept "collections as const" and do not face an exception that requires casting it to string[].
> feat: collections schema readonly

- packages/functions/README.md
- packages/functions/src/hooks/schemas/context.ts
- packages/functions/src/tests/hooks/schemas/context.spec.ts
For some scenario promise is not necessary for a run function, therefore it would be nice if it accepts void as well.
> feat: accept run function to return void

- packages/functions/README.md
- packages/functions/src/hooks/schemas/context.ts
- packages/functions/src/hooks/schemas/db/context.ts
Resolve following error when library is build with `tsc`:
```
❯ npm run build
> @junobuild/cli@0.2.0 build
> tsc --noEmit && node ./scripts/rmdir.mjs && node ./scripts/esbuild.mjs
node_modules/@junobuild/functions/hooks/schemas/context.d.ts:23:50 - error TS2536: Type 'k' cannot be used to index type 'addQuestionMarks<baseObjectOutputType<{ caller: ZodType<Uint8Array<ArrayBufferLike>, ZodTypeDef, Uint8Array<ArrayBufferLike>>; data: T; }>, any>'.
23 }>, any> extends infer T_1 ? { [k in keyof T_1]: z.objectUtil.addQuestionMarks<z.baseObjectOutputType<{
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
24     /**
~~~~~~~
... 
31     data: T;
~~~~~~~~~~~~
32 }>, any>[k]; } : never, z.baseObjectInputType<{
~~~~~~~~~~~
node_modules/@junobuild/functions/hooks/schemas/context.d.ts:41:46 - …
```
> fix: Zod - Type 'k' cannot be used to index type

- packages/admin/src/services/package.services.ts
A shorthand. Useful for the CLI in the `juno version` cmd.
> feat: get juno package version

- packages/admin/src/api/ic.api.ts
I've got this piece of code in the CLI and the warn are also annoying in the Console UI.
Therefore let's make the workaround to silence agent-js available in all consumers.
Relates to https://github.com/dfinity/agent-js/issues/843
> feat: disable agent-js console.warn

- packages/admin/src/services/package.services.ts
- packages/config/src/constants/juno.package.constants.ts
- packages/config/src/index.ts
It will be handy, both in the CLI and Console UI, to have a way to search for the satellite dependency in the Juno Package metadata.
> feat: find juno package dependency

- packages/admin/src/api/satellite.api.ts
- packages/admin/src/services/satellite.version.services.ts
Once I update the Console UI for backwards compatibility, it seems we do not use this elsewhere. So let's do a breaking change.
> feat: deprecated satellite build_version()

- packages/analytics/src/tests/api/orbiter.api.spec.ts
- packages/analytics/src/tests/index.spec.ts
- packages/analytics/src/tests/mocks/orbiter.mock.ts
- packages/analytics/src/tests/services/orbiter.services.spec.ts
- packages/analytics/src/tests/services/performance.services.spec.ts
- packages/analytics/src/tests/services/user-agent.services.spec.ts
- packages/analytics/src/tests/tracker.spec.ts
- packages/analytics/src/tests/tsconfig.json
- packages/analytics/src/tests/utils/analytics.utils.spec.ts
- packages/analytics/src/tests/utils/date.utils.spec.ts
- packages/analytics/src/tests/utils/dfinity/asserts.utils.spec.ts
- packages/analytics/src/tests/utils/dfinity/debounce.utils.spec.ts
- packages/analytics/src/tests/utils/dfinity/json.utils.spec.ts
- packages/analytics/src/tests/utils/dfinity/nullish.utils.spec.ts
- packages/analytics/src/tests/utils/env.utils.spec.ts
- packages/analytics/src/tests/utils/log.utils.spec.ts
- packages/analytics/src/tests/utils/window.env.utils.spec.ts
Out of nowhere Webstorm starts to not recognizing the vi global and show errors in every tests. Then a day later, it stops doing so. Then a day later it starts again etc.
Annoying. So let's move the tests in a separate folder since Webstorm recognize only a single tsconfig file.
> refactor: move tests - webstorm issue

- packages/analytics/src/services/user-agent.services.ts
```
Uncaught (in promise) TypeError: t is not a constructor
at ih.parseUserAgent (index.astro_astro_type_script_index_0_lang.BmfQMX7Q.js:48:30901)
at async Au (index.astro_astro_type_script_index_0_lang.BmfQMX7Q.js:48:31943)
```
> fix: uaparser dynamic import through default

- packages/analytics/src/tests/tracker.spec.ts
- packages/analytics/src/tests/utils/analytics.utils.spec.ts
- packages/analytics/src/tracker.ts
- packages/analytics/src/utils/analytics.utils.ts
If we collect campaign data separatly we don't want those in the href.
> feat: clean href when collecting campaign

- packages/admin/declarations/orbiter/orbiter.did.d.ts
- packages/admin/declarations/orbiter/orbiter.factory.certified.did.js
- packages/admin/declarations/orbiter/orbiter.factory.did.js
- packages/admin/declarations/orbiter/orbiter.factory.did.mjs
- packages/admin/declarations/satellite/satellite.did.d.ts
- packages/admin/declarations/satellite/satellite.factory.certified.did.js
- packages/admin/declarations/satellite/satellite.factory.did.js
- packages/admin/declarations/satellite/satellite.factory.did.mjs
- packages/admin/src/api/orbiter.api.ts
- packages/admin/src/api/satellite.api.ts
- packages/admin/src/services/orbiter.memory.services.ts
- packages/admin/src/services/satellite.memory.services.ts
- packages/core/declarations/satellite/satellite.did.d.ts
- packages/core/declarations/satellite/satellite.factory.certified.did.js
- packages/core/declarations/satellite/satellite.factory.did.js
- packages/core/declarations/satellite/satellite.factory.did.mjs
- packages/core/declarations/sputnik/sputnik.did.d.ts
- packages/core/declarations/sputnik/sputnik.factory.certified.did.js
- packages/core/declarations/sputnik/sputnik.factory.did.js
- packages/storage/declarations/satellite/satellite.did.d.ts
- packages/storage/declarations/satellite/satellite.factory.certified.did.js
- packages/storage/declarations/satellite/satellite.factory.did.js
- packages/storage/declarations/satellite/satellite.factory.did.mjs
We need the custom memory size endpoints for the CLI used in GH Actions.
> fix: revert custom memory_size usage

- packages/cli-tools/src/constants/deploy.constants.ts
We also want to serve HTML files on the web with gzip compression. This was pending because I never took the time to comebac to it as I though it was a tricky problem to resolve but actually, given that the CLI upload compressed files first, we can safely now gzip HTML as well.
> feat: compress HTML

- packages/cli-tools/src/services/deploy.prepare.services.ts
- packages/cli-tools/src/types/deploy.ts
When one submit a deploy proposal with clear, we need to submit all data not assert we only submit the differences because it's basically like a force all redeploy.
> feat: include all files option in pre-deploy

- packages/cli-tools/src/commands/deploy.ts
- packages/cli-tools/src/commands/upgrade.ts
- packages/cli-tools/src/services/deploy.proposal.services.ts
- packages/cli-tools/src/services/upload.services.ts
- packages/cli-tools/src/types/upgrade.ts
> ❯ node /Users/daviddalbusco/projects/juno/cli deploy --mode development --clear --no-apply
>   ✔ Uploading /index.html
>   ✔ Uploading /index.html
We do not want to display twice the full path but, want to diplsay the difference so we need to print the relative path to source (one is .html.gz)
> feat: redo sourceAbsolutePath for deploy

- packages/cli-tools/src/commands/upgrade.ts
- packages/cli-tools/src/services/upload.services.ts
- packages/cli-tools/src/types/deploy.ts
- packages/cli-tools/src/types/upgrade.ts
On one hand, pass the description this way we can use it to save the reference proposal / change ID, on the other, remove token from the main entry and use it only where needed, on upload file.
> feat: pass description as well for deploying assets with proposals

- packages/cli-tools/src/services/deploy.prepare.services.ts
I'm not sure if it's starlight or typedoc but, the build of the [documentation](https://github.com/dfinity/agent-js/tree/main/docs) of agent-js generate binary files.
e.g. `dist/core/pagefind/fragment/en_fe97e69.pf_fragment`
@ilbertt noticed that running `juno deploy` was always re-uploading those even though their content - i.e. related sha256 representation - did not changed.
After debugging, I noticed that the issue was actually related to a TODO that was left in place few years ago after implementing a solution to not reupload auto generated gzipped files.
> feat(cli-tools): avoid re-uploading binary file

- package-lock.json
- package.json
`npm ci` in the CI started failing (see https://github.com/junobuild/juno-js/actions/runs/16715542040).
This PR revert commit https://github.com/junobuild/juno-js/commit/af5da2301229eaf66bedb79dee03242039575a5d
> build(ci): fix package-lock

- packages/core/src/auth/services/user-webauthn.services.ts
- packages/core/src/tests/auth/services/user-webauthn.services.spec.ts
- packages/core/src/tests/mocks/webauthn.mock.ts
- packages/ic-client/src/tests/webauthn/aaguid.spec.ts
- packages/ic-client/src/tests/webauthn/credential.spec.ts
- packages/ic-client/src/webauthn/aaguid.ts
- packages/ic-client/src/webauthn/credential.ts
It's a bit a nicer interface. I still gonna save number[] in memory which takes a bit less space.
> feat(ic-client): use Uint8Array instead of number[] for aaguid

- packages/core/src/index.ts
This way clients do not have to import from ic-client.
> feat(core): re-export isWebAuthnAvailable

- packages/analytics/src/utils/window.env.utils.ts
- packages/core/src/core/utils/window.env.utils.ts
It seems that newest version of NextJS does not replace anymore the `process.env` that contains an optional chaining - i.e. `process.env?.NEXT_PUBLIC_SATELLITE_ID` is not replaced but, `process.env.NEXT_PUBLIC_SATELLITE_ID` is.
> fix(core): process.env optional chaining not replace in NextJS

- packages/cli-tools/src/constants/deploy.constants.ts
With the console I noticed that a batch of 50 worked well, so let's use it as default.
> feat(cli-tools): upload default batch size 50
